spring.application.name=exercice5

spring.datasource.url=jdbc:mysql://localhost:3306/demo_spring_secu
spring.datasource.username=${BDD_USER}
spring.datasource.password=${BDD_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


# Clé HMAC encode?e en Base64 (64 octets recommandés pour HS512)
security.jwt.secret=${TOKEN_SECRET}

# Durée d'expiration en millisecondes (ex. 1 jour)
security.jwt.expiration-ms=86400000